adjusts workflow

diff --git a/.github/workflows/brew_livechecks.yaml b/.github/workflows/brew_livechecks.yaml
--- a/.github/workflows/brew_livechecks.yaml
+++ b/.github/workflows/brew_livechecks.yaml
@@ -13,7 +13,7 @@ jobs:
     steps:
       - name: Set up Homebrew
         id: set-up-homebrew
-        uses: Homebrew/actions/setup-homebrew@v5
+        uses: Homebrew/actions/setup-homebrew@v4
       - name: Livecheck brew
         id: brew-checkver
         run: |
@@ -31,7 +31,7 @@ jobs:
           fetch-depth: 0
       - name: Set up Homebrew
         id: set-up-homebrew
-        uses: Homebrew/actions/setup-homebrew@v5
+        uses: Homebrew/actions/setup-homebrew@v4
       - name: Updates Formulas
         env:
           APPS: ${{needs.brew-livecheck.outputs.json-apps}}
@@ -40,11 +40,11 @@ jobs:
           brew install jq
           rm -f /tmp/.hashfailf
           touch /tmp/.hashfailf
-          update_version () { if [ ! -f ./Formula/${1}.rb ];then return 0;fi;formula=$1;new_version=$2;old_version=$3;awk -v old="$old_version" -v new="$new_version" '{if ($0 ~ /(url|version|bin\.[...]
+          update_version () { if [ ! -f ./Formula/${1}.rb ];then return 0;fi;formula=$1;new_version=$2;old_version=$3;awk -v old="$old_version" -v new="$new_version" '{if ($0 ~ /(url|version|bin\.install)/) {gsub(old, new, $0)};print $0 >"awk.out"}' ./Formula/${formula}.rb;mv awk.out ./Formula/${formula}.rb; }
           export -f update_version
-          update_hashs () { if [ ! -f ./Formula/${1}.rb ];then return 0;fi;formula=$1;paste -d ' ' <(pcregrep -o1 'url.*"(.*)"' ./Formula/${formula}.rb) <(pcregrep -o1 'sha256.*"(.*)"' ./Formula/$[...]
+          update_hashs () { if [ ! -f ./Formula/${1}.rb ];then return 0;fi;formula=$1;paste -d ' ' <(pcregrep -o1 'url.*"(.*)"' ./Formula/${formula}.rb) <(pcregrep -o1 'sha256.*"(.*)"' ./Formula/${formula}.rb) | xargs -L1 bash -c 'hash=$(curl -sL --fail $1 | sha256sum | cut -d " " -f 1;test ${PIPESTATUS[0]} -eq 0 || { echo "'${formula}'" >> /tmp/.hashfailf; });sed -ri "s/$2/$hash/g" ./Formula/'${formula}'.rb' bash; }
           export -f update_hashs
-          update_versions() { if [ ! -f ./Formula/${1}.rb ];then return 0;fi;if [ -f /tmp/.hashfailf ] && grep -qP '^'$1'$' "/tmp/.hashfailf";then return 0;fi;tmp=$(mktemp); jq '."'$1'" = "'$2'"' [...]
+          update_versions() { if [ ! -f ./Formula/${1}.rb ];then return 0;fi;if [ -f /tmp/.hashfailf ] && grep -qP '^'$1'$' "/tmp/.hashfailf";then return 0;fi;tmp=$(mktemp); jq '."'$1'" = "'$2'"' versions.json > "$tmp" && mv "$tmp" versions.json; }
           export -f update_versions
           echo "update version"
           echo "$APPS" | jq '.[] | select(.version.outdated) | "update_version \(.formula) \(.version.latest) \(.version.current)"' | xargs -n1 bash -c '$1' bash
@@ -66,11 +66,11 @@ jobs:
           brew install jq
           rm -f /tmp/.hashfailc
           touch /tmp/.hashfailc
-          update_version () { if [ ! -f ./Casks/${1}.rb ];then return 0;fi;formula=$1;new_version=$2;old_version=$3;awk -v old="$old_version" -v new="$new_version" '{if ($0 ~ /(url|version|bin\.in[...]
+          update_version () { if [ ! -f ./Casks/${1}.rb ];then return 0;fi;formula=$1;new_version=$2;old_version=$3;awk -v old="$old_version" -v new="$new_version" '{if ($0 ~ /(url|version|bin\.install)/) {gsub(old, new, $0)};print $0 >"awk.out"}' ./Casks/${formula}.rb;mv awk.out ./Casks/${formula}.rb; }
           export -f update_version
-          update_hashs () { if [ ! -f ./Casks/${1}.rb ];then return 0;fi;formula=$1;paste -d ' ' <(pcregrep -o1 'url.*"(.*)"' ./Casks/${formula}.rb) <(pcregrep -o1 'sha256.*"(.*)"' ./Casks/${formu[...]
+          update_hashs () { if [ ! -f ./Casks/${1}.rb ];then return 0;fi;formula=$1;paste -d ' ' <(pcregrep -o1 'url.*"(.*)"' ./Casks/${formula}.rb) <(pcregrep -o1 'sha256.*"(.*)"' ./Casks/${formula}.rb) | xargs -L1 bash -c 'hash=$(curl -sL --fail $1 | sha256sum | cut -d " " -f 1;test ${PIPESTATUS[0]} -eq 0 || { echo "'${formula}'" >> /tmp/.hashfailc; });sed -ri "s/$2/$hash/g" ./Casks/'${formula}'.rb' bash; }
           export -f update_hashs
-          update_versions() { if [ ! -f ./Casks/${1}.rb ];then return 0;fi;if [ -f /tmp/.hashfailc ] && grep -qP '^'$1'$' "/tmp/.hashfailc";then return 0;fi;tmp=$(mktemp); jq '."'$1'" = "'$2'"' ve[...]
+          update_versions() { if [ ! -f ./Casks/${1}.rb ];then return 0;fi;if [ -f /tmp/.hashfailc ] && grep -qP '^'$1'$' "/tmp/.hashfailc";then return 0;fi;tmp=$(mktemp); jq '."'$1'" = "'$2'"' versions.json > "$tmp" && mv "$tmp" versions.json; }
           export -f update_versions
           echo "update version"
           echo "$APPS" | jq '.[] | select(.version.outdated) | "update_version \(.cask) \(.version.latest) \(.version.current)"' | xargs -n1 bash -c '$1' bash
